# Generated by Django 3.2.4 on 2022-02-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayerrequest', '0007_alter_prayer_prayer_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer',
            name='prayer_answered_image',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='prayer_image',
        ),
    ]
