# Generated by Django 3.2.4 on 2022-02-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerboard', '0007_auto_20220205_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='prayer_answer_date',
            field=models.DateField(blank=True, null=True, verbose_name='prayer answer date'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='prayer_request_date',
            field=models.DateField(verbose_name='prayer request date'),
        ),
    ]
