# Generated by Django 4.0.3 on 2022-03-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerboard', '0009_alter_prayer_prayer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='prayer_title',
            field=models.CharField(default='Example Prayer Title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prayer',
            name='prayer_updates_user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='PrayerUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayers', models.ManyToManyField(to='prayerboard.prayer')),
            ],
        ),
    ]
